name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest

    steps:
      - uses: actions/checkout@v2

      - name:cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip3 install -r requirements.txt

          echo 'CML' > report.md
          cml-tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
          cml-send-comment report.md
          python train.py
          cml-send-comment report.md
