name: train-my-model

on: [push]

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - uses: iterative/setup-cml@v1

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          TB_CREDENTIALS: ${{ secrets.TB_CREDENTIALS }}
        run: |
          pip3 install -r requirements.txt
          
          cml-tensorboard-dev --logdir logs --md --name "Go to tensorboard" >> report.md
          cml-send-comment report.md
          python train.py
